[workspace]
resolver = "3"
members = ["dev-vpicc"]

[package]
name = "piv-authenticator"
version = "0.6.0"
authors = ["Nicolas Stalder <n@stalder.io>", "Nitrokey GmbH"]
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/nitrokey/piv-authenticator"
documentation = "https://docs.rs/piv-authenticator"

[[example]]
name = "vpicc"
required-features = []

[dependencies]
apdu-app = { version = "0.2", optional = true }
cbor-smol = { version = "0.5", features = ["heapless-bytes-v0-5"] }
delog = { version = "0.1.5", optional = true }
flexiber = { version = "0.2", features = ["derive", "heapless"] }
heapless = "0.9.1"
hex-literal = "1"
iso7816 = "0.2.0"
serde = { version = "1", default-features = false, features = ["derive"] }
trussed-auth = "0.5"
untrusted = "0.9"
log = "0.4"
heapless-bytes = "0.5.0"
subtle = { version = "2", default-features = false }
# TODO: only enable rsa features when needed
trussed-core = { version = "0.2", features = ["aes256-cbc", "chacha8-poly1305", "crypto-client", "ed255", "filesystem-client", "p256", "p384", "rsa2048", "rsa3072", "rsa4096", "shared-secret", "tdes", "x255"] }
trussed-rsa-types = { version = "0.2", optional = true }
trussed-chunked = "0.3.0"
trussed-hpke = "0.3.0"
trussed-wrap-key-to-file = "0.3.0"
littlefs2-core = "0.1.0"

[dev-dependencies]
dev-vpicc = { path = "dev-vpicc" }
vpicc = "0.1.0"
rand_core = { version = "0.10" }
env_logger = "0.10"
serde = { version = "1", features = ["derive"] }
serde_cbor = { version = "0.11", features = ["std"] }
hex  = "0.4"
test-log = "0.2.11"
ron  = "0.8"
des = "0.9"
aes = "0.9.2"
stoppable_thread = "0.2.1"
expectrl = "0.9.0"
iso7816 = { version = "0.2", features = ["std"] }

# Examples
# usbip
rand = "0.10"
asn1 = "0.24.1"

[features]
default = []
apdu-dispatch = ["dep:apdu-app"]
alloc = []
rsa = ["dep:trussed-rsa-types", "alloc"]
delog  = ["dep:delog"]

log-all = []
log-none = []
log-trace = []
log-debug = []
log-info = []
log-warn = []
log-error = []

[patch.crates-io]
trussed = { git = "https://github.com/trussed-dev/trussed", rev = "0f8df68be879acdde1f8cf428c11e5d29692a47b" }
trussed-auth-backend = { git = "https://github.com/trussed-dev/trussed-auth", tag = "backend-v0.1.0" }
trussed-rsa-alloc = { git = "https://github.com/trussed-dev/trussed-rsa-backend.git", tag = "v0.4.0" }
trussed-staging = { git = "https://github.com/trussed-dev/trussed-staging.git", tag = "v0.4.0" }

[profile.dev.package.rsa]
opt-level = 2

[profile.dev.package.num-bigint-dig]
opt-level = 2
