# Copyright (C) Nitrokey GmbH
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/trussed-dev/piv-authenticator
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@master
      - name: start pcscd
        run: pcscd -d -f --disable-polkit
        id: pcscd
        background: true
      - name: Install rust
        run: rustup show active-toolchain || rustup toolchain install
      - name: Run tests
        run: make ci
      - name: Upload tarpaulin html report
        uses: actions/upload-artifact@v7
        with:
          name: tarpaulin-html-report
          path: tarpaulin-report.html
      - name: Upload tarpaulin xml report
        uses: actions/upload-artifact@v7
        with:
          name: tarpaulin-xml-report
          path: tarpaulin-report.xml
      - name: Stop pcscd
        cancel: pcscd
