# Copyright (C) Nitrokey GmbH
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Install rust
        run: rustup show active-toolchain || rustup toolchain install
      - name: Run checks
        run: make lint
      - name: Run tests
        run: make test TEST_FEATURES="rsa,virt"
